export * from './admin.typeDefs'
export * from './amendity-property-type.typeDefs'
export * from './amenity-property.typeDefs'
export * from './amenity.typeDefs'
export * from './currency.typeDefs'
export * from './customer.typeDefs'
export * from './extraction.typeDefs'
export * from './media.typeDefs'
export * from './occupancy-status.typeDefs'
export * from './order.typeDefs'
export * from './property-condition.typeDefs'
export * from './property-mint.typeDefs'
export * from './property-style.typeDefs'
export * from './property-type.typeDefs'
export * from './property.typeDefs'
// export * from './rental-property-status.typeDefs'
export * from './wallet.typeDefs'